# Importações Necessárias

In [1]:
import numpy as np;
import pandas as pd;

# Parâmetros de Entrada

In [2]:
baseDados = "BPressureNishiBook.dat";
baseRegras = "BPressureNishiBook.txt";

# Pré-processamento

In [6]:
with open(baseDados, 'r') as arq:
    texto = arq.readlines();
    
mt = pd.DataFrame([[elemento for elemento in linha.split()] for linha in texto]);
mtBinaria = pd.get_dummies(mt);
mtBinaria = mtBinaria.astype('int').to_numpy();
print(MPR);

[[1 0 0 0 0 1 0 0 1 0 0 1 1 0 0 1 0 0]
 [1 0 0 0 0 1 1 0 0 0 0 1 0 1 0 0 0 1]
 [0 0 1 0 0 1 0 0 1 0 0 1 1 0 0 0 0 1]
 [0 0 1 0 0 1 0 0 1 0 0 1 1 0 0 1 0 0]
 [0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 1 0]
 [0 1 0 1 0 0 0 1 0 0 0 1 0 0 1 1 0 0]
 [0 1 0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1]
 [1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1]
 [0 1 0 0 1 0 0 1 0 1 0 0 1 0 0 0 1 0]
 [1 0 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1]
 [0 1 0 1 0 0 1 0 0 0 0 1 0 1 0 0 1 0]
 [0 1 0 0 1 0 0 0 1 0 0 1 0 1 0 0 1 0]
 [0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 1 0 0]
 [1 0 0 0 0 1 1 0 0 0 1 0 1 0 0 1 0 0]
 [0 0 1 0 0 1 0 0 1 0 0 1 1 0 0 0 1 0]]


# Calculo de Suporte

In [9]:
freqItens = np.sum(MPR, axis=0);
print(freqItens);
apoioItens = freqItens / MPR.shape[1];
print(apoioItens);


[ 5  6  4  3  3  9  4  5  6  2  3 10  9  3  3  5  5  5]
[0.27777778 0.33333333 0.22222222 0.16666667 0.16666667 0.5
 0.22222222 0.27777778 0.33333333 0.11111111 0.16666667 0.55555556
 0.5        0.16666667 0.16666667 0.27777778 0.27777778 0.27777778]
